// Generated by npm run build:java from OpenJDK 17.0.20.1.
import type { ToolchainManifest } from '../../toolchains/manifest'

export const javaCompiler: ToolchainManifest = {
  "id": "openjdk-javac",
  "version": "17.0.20.1",
  "assets": [
    {
      "path": "/javac-17.jar",
      "url": "javac-17.jar",
      "size": 3382993,
      "sha256": "b4de0fb85de30f73e37f9ab6452670d2c034d1c5ef848c86c5543e88a0477636"
    }
  ]
}
